start refactoring strategy block
kilokid/finance-assistance pull request #11
Opened 2021-08-27 09:42 UTC by kilokid

Начинаю рефакторить блок стратегии

2021-08-29 16:32 UTC, kilokid commented on src/sass/_strategy.sass
> +
Не могу сделать паддинги тайтлу и дискрипшину, тк сразу верстка съезжает, скорее всего из за того, что их ширина больше ширины экрана

2021-08-29 21:10 UTC, greatstudentkaze commented on src/sass/_strategy.sass
> +
А бокс-сайзинг здесь бордер-бокс?

2021-08-30 15:49 UTC, greatstudentkaze requested changes

2021-08-30 15:49 UTC, greatstudentkaze commented on src/index.html
> +              <span class="strategy-card__icon"></span>
иконку можно как img бахнуть с пустым альтом

2021-08-30 15:49 UTC, greatstudentkaze commented on src/index.html
> +              <span class="strategy-card__icon strategy-card__icon--white"></span>
лучше менять цвет иконки в зависимости от родительского модификатора

2021-08-30 15:49 UTC, greatstudentkaze commented on src/sass/_strategy.sass
> +        background-image: url(../img/blue-gear.svg)
иконки не надо свитчать на разных экранах
это фейл в дизайне

просто сделай какую-то карточку с шестеренкой, какую-то с человечками

2021-08-30 15:49 UTC, greatstudentkaze commented on src/sass/_strategy.sass
> +    width: 100%
блочные элементы же и так тянутся на всю ширину, не надо дублировать

2021-08-30 15:49 UTC, greatstudentkaze commented on src/sass/_strategy.sass
> +  &-card
аналогично этот блок в другой файл

2021-08-30 15:49 UTC, greatstudentkaze commented on src/index.html
> +          <p class="title strategy__title">Better Strategy With Quality Business</p>
вот тут кажется можно `h2`
на лендинге это ок по идее

2021-09-01 19:40 UTC, kilokid commented on src/index.html
> +              <span class="strategy-card__icon strategy-card__icon--white"></span>
не совсем понял как это сделать в моем случае

2021-09-01 20:53 UTC, merged