start ref menu
kilokid/finance-assistance pull request #13
Opened 2021-09-07 19:48 UTC by kilokid

2021-09-10 19:27 UTC, greatstudentkaze requested changes
hover, active, focus стейтов нет у ссылок и кнопок - грустно 😢 
остальное в тг написал

2021-09-10 19:27 UTC, greatstudentkaze commented on src/img/basket.svg
> +<svg width="24" height="23" viewBox="0 0 24 23" fill="none" xmlns="http://www.w3.org/2000/svg">
можно обжимать с svgo перед тем как в репу загружать

2021-09-10 19:27 UTC, greatstudentkaze commented on src/sass/blocks/_section.sass
> +  &-title
а поч элементы убрал?

2021-09-10 19:27 UTC, greatstudentkaze commented on src/index.html
> +                  <img src="img/basket.svg" alt="Icon: Basket">
лучше не писать icon, просто закидывай в альт то, что на иконке или картинке изображено

2021-09-10 19:27 UTC, greatstudentkaze commented on src/index.html
> +                  <img src="img/burger-menu.svg" alt="icon: Menu">
атрибуты width/height для свгшек особо важно!!! ну и для картинок в целом тоже важно

2021-09-10 19:27 UTC, greatstudentkaze commented on src/index.html
> +            <span class="menu__entrance">Login</span>
логин это переход на страницу логина в будущем, либо открытие попапа с входом, так что сделай ссылкой лучше

2021-09-10 19:27 UTC, greatstudentkaze commented on src/sass/blocks/_menu.sass
> +  font-style: normal
по моему по дефолту нормал, можно не задавать

аналогично с бордербоксом не понял, ты же для всего задавал бордербокс

2021-09-10 19:27 UTC, greatstudentkaze commented on src/sass/blocks/_menu.sass
> +    line-height: 24px
задавал эти свойства для всего хедера, зачем дублировать ?

2021-09-10 19:27 UTC, greatstudentkaze commented on src/sass/blocks/_menu.sass
> +    line-height: 22px
аналогично с дублиорованием

2021-09-10 19:27 UTC, greatstudentkaze commented on src/sass/blocks/_menu.sass
> +  &__button
ты не добавлял блок кнопки? она повторяется на макете

2021-09-10 23:32 UTC, kilokid commented on src/sass/blocks/_section.sass
> +  &-title
бэм ругался, а оборачивать  тайтлы с описанием в блок section не стал, решил сделать все отдельными блоками

2021-09-10 23:36 UTC, kilokid commented on src/sass/blocks/_menu.sass
> +  font-style: normal
забыл убрать, это я отдельно кое что тестил :(

2021-09-10 23:46 UTC, kilokid commented on src/sass/blocks/_section.sass
> +  &-title
хотя наверно лучше вынести это прям блоком с элементами, и вставлять в разметку как:
.section
     section__title
     section__description
     
   А пока у меня просто 
   .block
        h2.section-title block__title
        p.section-description block__description
        
И по такой схеме везде, нужно будет переписать

2021-09-11 10:10 UTC, greatstudentkaze commented on src/sass/blocks/_section.sass
> +  &-title
ага
ну отдельными блоками тоже можно

но тут просто эти тайтл и дескрипшн используются вместе постоянно
так что я подумал, что лучше сделать элементами одного блока

2021-09-13 18:24 UTC, greatstudentkaze requested changes
Активное меню на десктопе не должно работать! (скрин в телегу отправил)

2021-09-13 18:24 UTC, greatstudentkaze commented on src/js/modules/menu.js
> +  // Сделал твоим способом закрытие меню по клику вне его :)
klass!

2021-09-13 18:24 UTC, greatstudentkaze commented on src/js/modules/menu.js
> +    } else {
если выше просто выходишь из функции (return)
то можешь не писать else
пиши сразу closeMenu

2021-09-13 18:24 UTC, greatstudentkaze commented on src/js/modules/menu.js
> +  const menuItem = document.querySelector('.menu__links');
лучше menuElem, т.к. я когда прочитал подумал что menuItem это один из айтемов меню

2021-09-13 18:24 UTC, greatstudentkaze commented on src/sass/blocks/_menu.sass
> +.active
по БЭМу лучше делать модфикатор menu--active

2021-09-14 11:17 UTC, merged