fix: add login btn for mobile menu
kilokid/finance-assistance pull request #16
Opened 2021-09-16 12:35 UTC by kilokid

2021-09-16 12:37 UTC, kilokid commented
Пока добавил только одну кнопку, но если надо, добавлю и вторую (но меня пока и так устраивает)

2021-11-05 23:36 UTC, greatstudentkaze requested changes
Пам парам

2021-11-05 23:36 UTC, greatstudentkaze commented on src/js/modules/menu.js
> +    let expanded = menuButton.getAttribute('aria-expanded') === 'true' || false;
`const`
`isExpanded`

2021-11-05 23:36 UTC, greatstudentkaze commented on src/js/modules/menu.js
> +    let expanded = menuButton.getAttribute('aria-expanded') === 'true' || false;
И зачем еще || false ?

2021-11-05 23:36 UTC, greatstudentkaze commented on src/js/modules/menu.js
> +  const ariaAttribute = () => {
`toggleAriaAttribute` или как-то так
но я б ваще не стал это в отдельную функцию выносить

2021-11-05 23:36 UTC, greatstudentkaze commented on src/index.html
> +            <span class="menu__text menu__text-register">Become a member</span>
модификаторы другие
![image](https://user-images.githubusercontent.com/51622226/140588780-5a5531da-5995-4a90-ae08-a27a1f3e14ed.png)

2021-11-05 23:36 UTC, greatstudentkaze commented on src/index.html
> +      <ul class="menu__user">
тут бы user-list или что-то другое, но не user
user чет ваще никуда не ведет

2021-11-05 23:36 UTC, greatstudentkaze commented on src/sass/blocks/_menu.sass
>        &--active
лучше все статичные стили вынести из модификатора active
тут оставить только то что меняется
типа display: flex

2021-11-05 23:36 UTC, greatstudentkaze commented on src/sass/blocks/_menu.sass
> +      position: absolute
а у тя visually-hidden mixin есть или нет? если есть, то его используй
если нет – создай и используй

2021-11-05 23:36 UTC, greatstudentkaze commented on src/sass/blocks/_menu.sass
> +      margin-left: 12px
дублируется одинаковое значение у обоих модификаторов

2021-11-05 23:36 UTC, greatstudentkaze commented on src/sass/blocks/_menu.sass
> +        color: $white
color: white во всех стейтах чет не понятно зачем ? и зачем дублировать его тем более

2021-11-05 23:36 UTC, greatstudentkaze commented on src/sass/blocks/_menu.sass
> +      display: flex
так а тут флекс точно нужеН?

2021-11-05 23:36 UTC, greatstudentkaze commented on src/sass/blocks/_menu.sass
> +      &:active
я б вот эти изменения стейтов вкладывал с медиавыражением в изначальное
так проще искать потом

2021-11-05 23:36 UTC, greatstudentkaze commented on src/sass/blocks/_menu.sass
> +      &:active
сюда и сюда то есть 
![image](https://user-images.githubusercontent.com/51622226/140589253-540eeb8e-4e34-4c4e-ba41-58d741dc67ae.png)

2021-11-09 16:32 UTC, merged