create: latest-news block + change files structure
kilokid/finance-assistance pull request #2
Opened 2021-08-20 00:50 UTC by kilokid

Доделал news cards, пофиксил файловую структуру sass, пытался написать адаптив к блоку latest-news, но вышло каряво.
Есть вопросы по позиционированию контента внутри блоков card, и по их стилям
+ исправил мелкие ошибки

2021-08-20 00:57 UTC, kilokid commented on index.html
> +            <div class="header header_position">
Добавил элемент position, чтобы задать внешние отступы блоку

2021-08-20 00:57 UTC, kilokid commented on src/sass/blocks/_news.sass
> +    &__cards
проблема с блоком card, сделал +- похоже на макет, но есть разницы в контейнере, в котором они лежат. По макету видно что они на всю ширину страницы, но у меня не получилось это сделать, тк space-between не хочет растягивать их на всю ширину

2021-08-20 00:57 UTC, kilokid commented on src/sass/blocks/_news.sass
> +        width: calc(195px - (36px + 36px))
Когда задавал padding для контента, сам блок ломался, пришлось познакомится со свойством calc(), вроде помогло, но хотелось бы увидеть более удобный подход

2021-08-20 10:59 UTC, kilokid commented on src/sass/blocks/_container.sass
> +        max-width: 100%
Добавил width 100% для блока news__cards, но из за того, что у контента внутри карт есть padding 20, появилась горизонтальная прокрутка, не знаю как пофиксить :(
Если ставлю width меньше, то все краты прижимаются к правому краю

2021-08-20 13:52 UTC, greatstudentkaze commented on index.html
> +            <div class="header header_position">
элементы с двойным андерскором пишутся

2021-08-20 15:06 UTC, greatstudentkaze reviewed
Чекнул только первый вопрос по .header.header_position
Постараюсь посмотреть остальное вечером, сейчас ухожу

2021-08-20 15:06 UTC, greatstudentkaze commented on index.html
> +            <div class="header header_position">
![image](https://user-images.githubusercontent.com/51622226/130253624-8674b89e-9c2f-4cd8-8f8b-41ed7f47cf56.png)

`div.container`, `div.header` - лишние обертки в этом случае
тут будет достаточно задать тегу `header` класснейм `header` и `container`

2021-08-20 22:47 UTC, greatstudentkaze commented on src/sass/blocks/_container.sass
> +        max-width: 100%
box-sizing: border-box

2021-08-20 23:49 UTC, greatstudentkaze requested changes
Вроде все апдейты посмотрел
Верстку у себя открыл - фидбек написал в тг и тут

2021-08-20 23:49 UTC, greatstudentkaze commented on src/sass/blocks/_news.sass
> +
нужно уничтожить лишние переносы

2021-08-20 23:49 UTC, greatstudentkaze commented on src/sass/blocks/_news.sass
> +    &__button
делай переносы строк после элементов плз

```sass
margin-bottom: 15px

    &__button
```

2021-08-20 23:49 UTC, greatstudentkaze commented on css/style.css
> +.button{font-weight:700;font-size:14px;line-height:22px;text-align:center;letter-spacing:0.2px;background-color:#23A6F0;border-radius:37px;padding:15px 37px;color:#fff;cursor:pointer}.button_white{ba
папку css надо удалить и закоммитить то, что ты ее удалил

2021-08-20 23:49 UTC, greatstudentkaze commented on src/index.html
>              <div class="container">
лишняя вложенность, можно замиксовать news и container

2021-08-20 23:49 UTC, greatstudentkaze commented on src/index.html
> +            <div class="news__cards container container__news">
лучше не надо элементы у container делать (блок со своим элементом не может быть одной сущностью)
здесь можно просто ограничить ширину у элемента news__cards

2021-08-20 23:49 UTC, greatstudentkaze commented on src/index.html
> +                <div class="news__card news__bg news__bg_1">
news__bg лишний элемент
news__card + модификатор news__card--1 -- ок

2021-08-20 23:49 UTC, greatstudentkaze commented on src/sass/blocks/_news.sass
> +        padding-top: 112px
лучше сделать верхний отступ для секции а не для тайтла
писал в тг

2021-08-20 23:49 UTC, greatstudentkaze commented on src/sass/blocks/_news.sass
> +        margin-top: 96px
также лучше сделать margin-bottom у `news__description`
и вместо margin-bottom padding-bottom у всей секции

2021-08-20 23:49 UTC, greatstudentkaze commented on src/sass/blocks/_news.sass
> +        max-width: 168px
![image](https://user-images.githubusercontent.com/51622226/130301704-a1286b4d-0a21-48a2-bed0-20b6d135a6bc.png)

мне кажется, лучше будет убрать ограничение по ширине (чтобы кнопка тянулась на всю карточку по контенту)
чтобы она не растягивалась на всю карточку (карточка flex), нужно задать правильный align-self ей

2021-08-20 23:49 UTC, greatstudentkaze commented on src/sass/blocks/_news.sass
> +    &__bg
при переполнении контента картинка не растягивается по всей карточке
![image](https://user-images.githubusercontent.com/51622226/130301968-1f018359-85de-413e-a065-c3a1e22f71bc.png)

2021-08-20 23:49 UTC, greatstudentkaze commented on src/sass/blocks/_news.sass
> +    &__cards
![image](https://user-images.githubusercontent.com/51622226/130302045-6e9dd65d-2979-4556-a65c-2eb91552065f.png)

если одна карточка больше других по контенту
то другие не растягиваются до ее высоты (думаю, тут такое поведение будет наиболее правильным)

2021-08-20 23:49 UTC, greatstudentkaze commented on src/sass/blocks/_news.sass
> +            grid-gap: 20px
сейчас можно использовать просто `gap`
но по-моему оно плохо работает в сафари ниже 15 версии (не применяются тупо и твои карточки слипнутся)
так что лучше либо гридами сверстать
либо сделать марджинами

2021-08-20 23:49 UTC, greatstudentkaze commented on src/index.html
>          <div class="news">
для таких секций можно использовать тег `section`

2021-08-20 23:49 UTC, greatstudentkaze commented on src/sass/_base.sass
> +    box-sizing: border-box
забыл про ::before и ::after

2021-08-20 23:49 UTC, greatstudentkaze commented on src/sass/_base.sass
> +    box-sizing: border-box
+ как по мне лучше задать для всех элементов и псевдоэлементов свойство inherit (чтобы наследовалось)
и для html, body задать уже `box-sizing: border-box`

тогда если нам понадобится использовать какой-то другой box-sizing для какого-то элемента
нам достаточно будет к нему применить новый box-sizing
и оно будет применено ко всем дочерним

2021-08-20 23:49 UTC, greatstudentkaze commented on src/sass/_base.sass
>      font-family: 'Montserrat', sans-serif
нужно добавить после Montserrat веб-безопасный шрифт (в идеале очень похожий на него)

список веб-безопасных шрифтов
https://www.cssfontstack.com/

2021-08-20 23:49 UTC, greatstudentkaze commented on src/sass/_base.sass
>      font-family: 'Montserrat', sans-serif
вот хороший доклад по шрифтам от Вадима Макеева - https://www.youtube.com/watch?v=uI3Q5m9xkkw
вроде там он должен говорить зачем вебсейф шрифты нужны

2021-08-20 23:49 UTC, greatstudentkaze commented on src/sass/blocks/_button.sass
> -    cursor: pointer
лучше оставить cursor: pointer
т.к. у тега button его нет по дефолту

2021-08-20 23:49 UTC, greatstudentkaze commented on src/index.html
> +            <div class="main main_position">
аналогично header
миксовать блок с его элементом нинада

2021-08-20 23:50 UTC, greatstudentkaze commented on src/sass/blocks/_news.sass
> +    &__button
я могу добавить линтер для таких штук
чтоб он тебя по рукам бил там где ты кодстайлу не соответствуешь

2021-08-20 23:52 UTC, greatstudentkaze commented on src/sass/blocks/_news.sass
> +            grid-gap: 20px
плохо работает во флексах*

2021-08-20 23:56 UTC, kilokid commented on src/sass/blocks/_news.sass
> +    &__button
тогда еще не использовал кодстайл, начал только с pricing, отрефакторю news завтра

2021-08-21 20:38 UTC, greatstudentkaze commented on index.html
> +            <div class="header header_position">
а , это модификатор... тупанул + забыл

2021-08-22 22:58 UTC, kilokid commented on src/sass/_base.sass
> +    box-sizing: border-box
немного не понял что имеешь ввиду

2021-08-22 23:02 UTC, kilokid commented on src/sass/_base.sass
> +    box-sizing: border-box
все, понял

2021-08-23 09:39 UTC, greatstudentkaze commented on src/sass/_base.sass
> +    box-sizing: border-box
Я НАВРАЛ

2021-08-23 12:58 UTC, kilokid commented on src/sass/blocks/_news.sass
> +    &__cards
не совсем понял, лучше чтобы растягивались, или нет?

2021-08-27 13:36 UTC, greatstudentkaze requested changes
Это ласт проверка по этому блоку
Но есть над чем поработать

Перепроверь зарезолвленные таски, как будто есть resolved comments там где нет правок/обсуждений

Как все поправишь, жди проверки Pricing
После этого мерджим Pricing сюда
И эту ветку в главную

2021-08-27 13:36 UTC, greatstudentkaze commented on src/sass/_base.sass
> +    box-sizing: border-box
*,
::before,
::after {
....
}

вот так можно, чтобы не дублировать

2021-08-27 13:36 UTC, greatstudentkaze commented on src/sass/blocks/_top-menu.sass
> +    @media (max-width: 768px)
медиавыражения лучше складывать после основных стилей (для нормального каскада)

если это временно - ок

2021-08-27 13:36 UTC, greatstudentkaze commented on src/sass/blocks/_section.sass
> +.title
я тут имел в виду создать блок `section`
и у него элементы `__title` `__description`
также этому `section` можно добавить отступы, которые повторяются у каждого блока

2021-08-27 13:36 UTC, greatstudentkaze commented on src/sass/blocks/_card.sass
> +.card
не нашел где используется этот блок в news 🤯

2021-08-27 13:36 UTC, greatstudentkaze commented on src/sass/blocks/_news.sass
> +      padding: 0 25px
я бы уменьшил до 20px
чтобы на 320 и около того заголовок в две строки не складывался

15-20 по бокам на телефонах - ок, больше кажется, не надо
только если дизайн не говорит так делать

2021-08-27 13:36 UTC, greatstudentkaze commented on src/sass/blocks/_news.sass
> +    gap: 30px
gap со флексами плохо работает в safari!
с gap используй grid
либо сделай отступы марджинами

2021-08-27 13:36 UTC, greatstudentkaze commented on src/sass/blocks/_news.sass
> +    align-items: stretch
верхний `align-items` можно убрать
ты его перезаписываешь

2021-08-27 13:36 UTC, greatstudentkaze commented on src/sass/blocks/_news.sass
> +  &__bg
по-моему писал уже что не ок элементы одного блока миксовать

да , вот:
![image](https://user-images.githubusercontent.com/51622226/131135103-bb7f8db8-2466-44a1-ba0f-d8f7b92d2691.png)

\+ ты часть свойств `background` пишешь в `__card` часть в `__bg`, как-то нелогично

и там возможно еще какие-то таски зарезловлены, но остались без комментов и изменений

2021-08-29 17:04 UTC, kilokid commented on src/sass/blocks/_card.sass
> +.card
это от блока reviews, сейчас подумаю нужно ли мне вообще выносить это отдельно

2021-09-03 15:26 UTC, merged