Create block Pricing
kilokid/finance-assistance pull request #4
Opened 2021-08-20 14:11 UTC by kilokid

Сделал блок pricing и прописал его скелет, начинаю писать стили для pricing cards

2021-08-21 10:28 UTC, greatstudentkaze commented on .editorconfig
> +oot = true
root *

2021-08-21 17:39 UTC, kilokid commented on src/sass/blocks/_pricing.sass
> +.pricing
сама структура карт в разметке очень плохо вышла, как по мне. Поэтому не смог сделать, чтобы при адаптиве прайс уезжал вправо. Пока думаю как это лучше реализовать

2021-08-21 17:47 UTC, greatstudentkaze commented on src/sass/blocks/_pricing.sass
> +.pricing
подсказка
![image](https://user-images.githubusercontent.com/51622226/130330656-cc035992-1d0e-4963-8d95-30d04bd41dba.png) ![image](https://user-images.githubusercontent.com/51622226/130330662-db3c7f19-0d4d-4cd3-9c95-2244520424b3.png)

сделай цену плюс частоту одним блоком
число, валюту и частоту в отдельные span

2021-08-21 17:48 UTC, greatstudentkaze commented on src/sass/blocks/_pricing.sass
> +.pricing
использовать flex/grid можно

2021-08-21 17:49 UTC, greatstudentkaze commented on src/sass/blocks/_pricing.sass
> +.pricing
с grid кажется совсем просто можно реализовать

2021-08-23 17:59 UTC, greatstudentkaze requested changes
Прошелся по коду и сам компонент посмотрел
Добавил комменты сюда и в ноушене в таск

Напиши, как все поправишь
Сам еще перепроверься, мб сам увидишь что-то

2021-08-23 17:59 UTC, greatstudentkaze commented on src/index.html
> +              <p class="pricing__card-rate">FREE</p>
это тариф - тайтл карточки
можно задать `h3`

2021-08-23 17:59 UTC, greatstudentkaze commented on src/index.html
> +              <p class="pricing__card-subscription">Per Month</p>
цену и частоту мне кажется в одном параграфе хранить :
0$ - что ноль долларов ?
Per month - что в месяц ?
0$ per month - ноль долларов в месяц

и спанами разбить, если стилизация разная

2021-08-23 17:59 UTC, greatstudentkaze commented on src/index.html
> +              <div class="wrapper--flex">
модификатор должен записываться со своим блоком !

2021-08-23 17:59 UTC, greatstudentkaze commented on src/index.html
> +            <div class="card card--border pricing__card">
яб переназвал это с `card`
все-таки это не просто карточка
`pricing-card` норм

2021-08-23 17:59 UTC, greatstudentkaze commented on src/index.html
> +            <p class="description pricing__description">Problems trying to resolve the conflict between the two major realms of Classical physics: Newtonian mechanics </p>
когда большой текст лучше его переносить таким образом:
```html
<p>
  ..............................
</p>
```

2021-08-23 17:59 UTC, greatstudentkaze commented on src/index.html
> +                    <img class="pricing__card-cheked" src="./img/included-check.png" alt="Icon: Active check mark">
кажется, загружаем лишнее

можно кружочки by CSS рисовать
и сверху класть галочку

2021-08-23 17:59 UTC, greatstudentkaze commented on src/index.html
> +                    <img class="pricing__card-cheked" src="./img/included-check.png" alt="Icon: Active check mark">
альт, думаю, можно просто Active оставить
кажется, скринридер много читать будет 

но я прям 100% не могу сказать какой лучший подход тут
надо поискать ответы

2021-08-23 17:59 UTC, greatstudentkaze commented on src/index.html
> +                    <span class="pricing__card-features">Unlimited product updates</span>
вроде без спанчика можно
а оттолкнуть текст стилями иконки
но такой подход не ошибка

2021-08-23 17:59 UTC, greatstudentkaze commented on src/index.html
> +              <p class="pricing__card-rate">FREE</p>
полубемчик получаеца

просто делаешь блок - `pricing-card`, например
и у него элементами будут все вот эти -rate -description -subscription итэдэ

2021-08-23 17:59 UTC, greatstudentkaze commented on src/index.html
> +              <div class="wrapper--flex">
да и тут можно просто
`pricing-card__wrapper`
не надо из этого отдельный блок делать

2021-08-23 17:59 UTC, greatstudentkaze commented on src/index.html
> +                <div class="wrapper">
+1 к тому что не нужно отдельным блоком делать

яб `ul` использовал вообще
ну и класснейм `pricing-card__features` какой-нибудь

2021-08-23 17:59 UTC, greatstudentkaze commented on src/index.html
> +            <div class="card card--border pricing__card pricing__card_new">
либо один синтаксис модификаторов `--`, либо второй `_` используй

2021-08-23 17:59 UTC, greatstudentkaze commented on src/index.html
> +              <div class="pricing__card-chevron">New</div>
можно тож параграфом

2021-08-23 17:59 UTC, greatstudentkaze commented on src/sass/blocks/_button.sass
> +
```css














```

2021-08-23 17:59 UTC, greatstudentkaze commented on src/sass/blocks/_card.sass
> +    border: 1px solid $blue
можно просто цвет рамки менять

2021-08-23 17:59 UTC, greatstudentkaze commented on src/sass/blocks/_card.sass
> +  &--border
непонятный модификатор по названию
`--large-border-radius` как вариант

2021-08-23 17:59 UTC, greatstudentkaze commented on src/sass/blocks/_pricing.sass
> +  @media (max-width: 520px)
это к чему медиа-выражение? кажется съехало

2021-08-23 17:59 UTC, greatstudentkaze commented on src/sass/blocks/_pricing.sass
> +      display: flex
зочем дублируем, молодой человек

про каскад свойств знаешь ведь? или случайно добавил

CSS - cascading stylesheets

2021-08-23 17:59 UTC, greatstudentkaze commented on src/sass/blocks/_pricing.sass
> +    min-height: 589px
а там контентом не распирает до нужной высоты?

2021-08-23 17:59 UTC, greatstudentkaze commented on src/sass/blocks/_pricing.sass
> +      font-size: 16px
чтобы не дублировать одни и те же свойства можно прописать их выше где-нибудь
на уровне карточки, например
и так везде надо, я раньше чет не обращал внимания

2021-08-23 17:59 UTC, greatstudentkaze commented on src/sass/blocks/_pricing.sass
> +
```css






```

2021-08-23 17:59 UTC, greatstudentkaze commented on src/sass/blocks/_pricing.sass
> +.wrapper
оч странный блок

2021-08-23 17:59 UTC, greatstudentkaze commented on src/sass/blocks/_pricing.sass
> +.wrapper
и не туда попал

2021-08-25 00:40 UTC, kilokid commented on src/sass/blocks/_pricing.sass
> +    &__price
пытался чото наколдовать на гридах, но не особо вышло. Завтра перечитаю использование гридов, и попробую снова

2021-08-26 00:34 UTC, kilokid commented on src/sass/blocks/_pricing.sass
> +    &__price
с гридами не особо разобрался, попробовал с vertical align чото сделать, почти получилось, но центровка уезжает то у одного блока, то у другого (если меняю свойства тому). Голова уже кипит с этим блокам, очень жесткий затуп пошел, завтра опять буду над ним разбираться

2021-08-26 19:30 UTC, greatstudentkaze commented on src/sass/blocks/_pricing.sass
> +    &__price
: - (
подскзка - можно использовать `grid-template-areas` / `grid-row` / `grid-column`

ну, если совсем никак будет, могу показать

2021-08-26 21:23 UTC, kilokid commented on src/sass/blocks/_pricing.sass
> +    &__price
хочу сам решить эту задачу, а если не получится, то на самый крайний случай уже попрошу подробно объяснить 💗

2021-08-29 19:32 UTC, kilokid commented on src/sass/blocks/_pricing.sass
> +    &__price
FINISH!

2021-09-03 14:21 UTC, merged