create get in touch
kilokid/finance-assistance pull request #7
Opened 2021-08-21 19:21 UTC by kilokid

initialized the block get-in-touch

2021-08-22 07:18 UTC, greatstudentkaze commented
![image](https://user-images.githubusercontent.com/51622226/130346112-5f6f9681-5e7f-41e3-adc0-d7a953625c5c.png)
Можно чуть раньше менять, чтобы так не слеплялись

2021-08-22 07:18 UTC, greatstudentkaze commented
У инпута с кнопкой есть рамка по дизайну

![image](https://user-images.githubusercontent.com/51622226/130346188-ace5ec5c-6006-42d8-a895-a024d76c0571.png)

2021-08-22 07:20 UTC, greatstudentkaze commented
Из-за того что фиксированные размеры заданы элементы не тянутся на всю ширину контейнера

![image](https://user-images.githubusercontent.com/51622226/130346212-5dcfbbb0-25ac-4871-b5a5-4a4314a96956.png)

2021-08-22 07:22 UTC, greatstudentkaze commented
Шрифт в инпуте и кнопке не соответствует дизайну

Expected:
![image](https://user-images.githubusercontent.com/51622226/130346248-688e1637-6787-4848-96cd-5de951296bed.png)

Actual:
![image](https://user-images.githubusercontent.com/51622226/130346237-4d29c302-5efb-4213-b618-dfbf29d01cea.png)

2021-08-22 07:58 UTC, greatstudentkaze requested changes
Прошелся по всем измененным файлам, добавил комментарии

Не забывай **резолвить** эти комментарии, как внесешь правки - чтобы я понимал, что с этим готово
Нужно резолвить ***все*** комменты по пуллреквесту, если в каком-то есть сомнения, что я прав, или непонятка почему так надо делать - пиши свой reply comment

Как все сделаешь, напиши мне

2021-08-22 07:58 UTC, greatstudentkaze commented on src/index.html
> +              <form action="">
action можно убрать, т.к. это для себя сайтик и тут логики никакой нет

2021-08-22 07:58 UTC, greatstudentkaze commented on src/sass/_base.sass
> +    display: inline-block
Лучше не задавать такие свойства ко всем ссылкам на странице
Вдруг нам понадобится использовать ссылку внутри текста? Тогда нужно будет переопределять поведение, которое мы указали в base.sass

2021-08-22 07:58 UTC, greatstudentkaze commented on src/index.html
> +                <input class="get-touch__input get-touch__input-email" type="text" name="" placeholder="Your Email">
email это модификатор или элемент?

2021-08-22 07:58 UTC, greatstudentkaze commented on src/index.html
> +                <input class="get-touch__input get-touch__input-email" type="text" name="" placeholder="Your Email">
name либо просто убери, либо задай значение какое-то (email, например)
также поле сделай required, т.к. сейчас я могу отправить форму не заполнив его

2021-08-22 07:58 UTC, greatstudentkaze commented on src/index.html
> +                <input class="get-touch__input get-touch__input-email" type="text" name="" placeholder="Your Email">
для электронной почты есть input[type="email"] у него есть нативная валидация email

2021-08-22 07:58 UTC, greatstudentkaze commented on src/index.html
> +                <input class="get-touch__input get-touch__input-button" type="submit" name="" value="Subscribe">
этому инпуту можно убрать name

2021-08-22 07:58 UTC, greatstudentkaze commented on src/index.html
> +          <!-- Не объединяю, тк фон на весь блок, а контент определенной ширины -->
да, правильно

2021-08-22 07:58 UTC, greatstudentkaze commented on src/index.html
> +            <div class="get-touch__right">
useless обертка в этом конкретном случае
у тебя сразу в ней идет `form`, который оборачивает все

2021-08-22 07:58 UTC, greatstudentkaze commented on src/sass/_get-touch.sass
> +    &-button
Не учтено переполнение контентом
![image](https://user-images.githubusercontent.com/51622226/130346599-4e2012a2-b4c9-4fb5-87ca-07304b874e9f.png)

2021-08-22 07:58 UTC, greatstudentkaze commented on src/sass/_get-touch.sass
> +    @media (max-width: 930px)
зачем дублирование медиа-выражения? можно все в одном

2021-08-22 07:58 UTC, greatstudentkaze commented on src/index.html
> +            <div class="get-touch__left">
конечно бывает ок такой нейминг
но вдруг понадобится поменять эти блоки местами?
![image](https://user-images.githubusercontent.com/51622226/130346676-147fdd16-12e4-427e-942a-4c57dacc637a.png)

тогда это уже не левый
старайся использовать более описательные названия
первое что приходит в голову - __info
правый блок у тебя форма, можно __form

2021-08-22 07:58 UTC, greatstudentkaze commented on src/sass/_get-touch.sass
> +    @media (max-width: 352px)
старайся использовать более менее одинаковые ширины изменения контента (по всему сайту)
например, 375px (iphone 6 7 8 X)

можно использовать кастомные, но в оооооооочень крайних случаях

2021-08-22 07:58 UTC, greatstudentkaze commented on src/sass/_get-touch.sass
> +    transition: 0.5s
лучше не задавать `transition: all`
всегда старайся конкретизировать это свойство, чтобы браузер не анимировал лишнего

2021-08-22 07:58 UTC, greatstudentkaze commented on src/sass/_get-touch.sass
> +      height: 58px
фиксированная ширина - useless
добейся ширины по макету padding и контентом внутри инпута

2021-08-22 07:58 UTC, greatstudentkaze commented on src/sass/_get-touch.sass
> +      outline: none
не надо убирать outline

вот я с клавиатуры перешел на инпут:
![image](https://user-images.githubusercontent.com/51622226/130346852-045cb348-b244-42b4-a0b9-08440387cd9d.png)
как мне кроме курсора быстро понять, что я тут?

если хочешь убрать дефолтный outline, то поработай со стилями псевдоклассов так, чтобы все состояния интерактивного элемента (кнопка, ссылка и прочее) были учтены

2021-08-22 07:58 UTC, greatstudentkaze commented on src/sass/_get-touch.sass
> +      padding: 15px 20px
padding куда-то не туда затесался, закинь его к размерам лучше

2021-08-22 07:58 UTC, greatstudentkaze commented on src/sass/_get-touch.sass
> +      border-radius: 5px 0 0 5px
я б лучше эти свойства использовал вместо составного

![image](https://user-images.githubusercontent.com/51622226/130346939-e83383de-f812-4462-817d-3c00ffa2193d.png)

чтобы не думать

2021-08-22 07:58 UTC, greatstudentkaze commented on src/sass/_get-touch.sass
> +      width: 270px
для адаптивности лучше не использовать фиксированные размеры
```css
width: 100%;
max-width: 270px;
```
как вариант

2021-08-22 12:26 UTC, kilokid commented on src/sass/_get-touch.sass
> +    &-button
не могу понять как это сделать, чтобы кнопка не выпадала и контент нормально помещался, а не уходил куда то вправо 
![image](https://user-images.githubusercontent.com/79492597/130355094-297c8a53-4a9b-4583-b269-ba51b16edb40.png)

2021-08-22 12:28 UTC, kilokid commented on src/sass/_get-touch.sass
> +      width: 270px
сделал так 
![image](https://user-images.githubusercontent.com/79492597/130355139-abd914d3-d8d6-4206-9752-9b99051986d2.png)
, тк если если поставить 100%, то кнопка переходит на другую строку 
![image](https://user-images.githubusercontent.com/79492597/130355172-a081128a-3198-4287-a95f-9416e0ba6379.png)

2021-08-22 12:53 UTC, greatstudentkaze commented on src/sass/_get-touch.sass
> +      width: 270px
значит `max-width` большой
ширину отличную от 100% ни нада

2021-08-22 12:54 UTC, greatstudentkaze commented on src/sass/_get-touch.sass
> +    &-button
сделай этот элемент флексовым
ограничь ширину кнопки
сделай инпут растягивающимся на всю возможную ширину

2021-08-23 13:43 UTC, greatstudentkaze commented
approved with minor changes 👍🏼

2021-09-03 15:32 UTC, merged