create: footer
kilokid/finance-assistance pull request #9
Opened 2021-08-22 20:56 UTC by kilokid

Сверстал футер, жду ревью

2021-08-23 14:28 UTC, greatstudentkaze requested changes
Проверил, нужно внести правки
Написал про проблемы с вёрсткой в телеграме

Напиши, как все поправишь

2021-08-23 14:28 UTC, greatstudentkaze commented on src/index.html
> +              <a class="top-footer__social-item" href="#"><img src="./img/facebook.svg" alt="Icon: facebook link"></a>
для читабельности можно img на следующую строку перенести

2021-08-23 14:28 UTC, greatstudentkaze commented on src/index.html
> +              <li class="top-footer__item">About Us</li>
эти все элементы - ссылки на другие страницы
так что нужно текст еще в ссылку обернуть

2021-08-23 14:28 UTC, greatstudentkaze commented on src/index.html
> +      <div class="top-footer">
лишняя обертка -- зачем?
можно сразу на футер ведь

2021-08-23 14:28 UTC, greatstudentkaze commented on src/index.html
> +          <div class="top-footer__card top-footer__get-touch">
я могу ошибаться
но по-моему элементы одного блока миксовать нельзя

\+ здесь и в других __card футера эти селекторы никак не используются

2021-08-23 14:28 UTC, greatstudentkaze commented on src/index.html
> +          <div class="top-footer__card top-footer__get-touch">
если бы у каждого была специфическая стилизация
я бы сделал .top-footer__block + .top-footer__block--get-in-touch (добавлял бы модификатор для отличающегося блока)

2021-08-23 14:28 UTC, greatstudentkaze commented on src/sass/_top-footer.sass
> +  &__social-item:not(:last-child)
можно вложить

2021-08-23 14:28 UTC, greatstudentkaze commented on src/sass/_top-footer.sass
> +    &--first
лучше `--get-in-touch`

либо добавить модификатор блоку 
и здесь использовать `CLASSNAME--get-in-touch & `

2021-08-23 14:28 UTC, greatstudentkaze commented on src/sass/_top-footer.sass
> +  &__social-item:not(:last-child)
я бы этим штукам интерактивности добавил

2021-08-23 14:28 UTC, greatstudentkaze commented on src/sass/style.sass
> +
не пойму зачем отступы прям после каждого импорта 

![sticker](https://user-images.githubusercontent.com/51622226/130464562-1c975ac3-ae9a-4406-9fda-387283f85c27.jpg)

2021-08-23 16:12 UTC, kilokid commented on src/sass/_top-footer.sass
> +  &__social-item:not(:last-child)
например?

2021-08-23 18:03 UTC, greatstudentkaze commented on src/sass/_top-footer.sass
> +  &__social-item:not(:last-child)
хотя бы прозрачность менял при наведении, фокусе и нажатии

если бы это инлайновые свгшки были, то можно было бы цвет изменять

2021-08-27 14:07 UTC, greatstudentkaze requested changes
В основном все ок!
Небольшие изменения нужно внести, так что это последняя проверка

Самостоятельно сверься с дизайном еще, можешь попробовать PixelPerfect плагин

Как поправишь все, мерджи в `main`

2021-08-27 14:07 UTC, greatstudentkaze commented on src/sass/_top-footer.sass
> +  &__item:not(:last-child)
можно вложить, и выше тоже

2021-08-27 14:07 UTC, greatstudentkaze commented on src/sass/_top-footer.sass
> +  &__item:not(:last-child)
я имел в виду так вложить, а не `&-item` (так не очень т.к. раздувание вложенности)

```scss
  &__social-item
    &:not(:last-child)
```

2021-08-27 14:07 UTC, greatstudentkaze commented on src/index.html
> +              <img src="./img/facebook.svg" alt="Icon: facebook link">
для консистентности используй одинаковые пути (без `./`)

2021-08-29 20:20 UTC, kilokid commented on src/sass/_top-footer.sass
> +  &__item:not(:last-child)
![image](https://user-images.githubusercontent.com/79492597/131264147-445820ce-baa9-4ee0-abba-28585b901d22.png)

Так? просто не совсем понял, у меня там блок social, которому задано внутреннее позиционирование, если я сделаю его сразу $__social-item, то не смогу задать display flex

2021-08-29 20:48 UTC, greatstudentkaze commented on src/sass/_top-footer.sass
> +  &__item:not(:last-child)
да, первый так

второй также ток ищо
```scss
  &__item
    &:not(:last-child)
```

2021-09-03 15:35 UTC, merged